### PR TITLE
Update benchmark to use non-legacy template

### PR DESCRIPTION
**Pull request by alexellis**
Signed-off-by: Alex Ellis <alexellis2@gmail.com>

The original author appears not to have see the documentation
on performance testing and benchmarking with OpenFaaS. This commit
updates the example to perform at representative speed.

Ref:
https://docs.openfaas.com/architecture/performance/

### CODE REVIEW

**Comment by alexellis** [comment]
Please merge this PR then run `faas-cli build/push` followed by re-running your tests.

Unfortunately the damage has already been done with the slides you presented, but there is the opportunity to make a correction and to update your slides.

Thanks for your cooperation,

Alex

**Comment by lreimer** [comment]
Hey @alexellis 
Thanks for the PR. I will rerun the tests and update the slides!

**Comment by lreimer** [comment]
Regarding the legacy template: I followed the instructions in the docs. https://docs.openfaas.com/cli/templates/

**Comment by lreimer** [comment]
```
Running 30s test @ http://openfaas.demo/function/hello-openfaas
  4 threads and 50 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency   149.16ms  194.23ms   1.96s    89.40%
    Req/Sec   130.52     63.46   280.00     64.01%
  13203 requests in 30.07s, 3.15MB read
  Socket errors: connect 0, read 0, write 0, timeout 26
Requests/sec:    439.05
Transfer/sec:    107.19KB
```

**Comment by lreimer** [comment]
Stats have improved. In the simple scenario we get 439 Requests/sec now.

**Comment by alexellis** [comment]
This seems low compared to our testing.

**Comment by alexellis** [comment]
What Docker image did you deploy?

**Comment by lreimer** [comment]
the newly build image from your PR using the new go-middleware mechanism

**Comment by alexellis** [comment]
How are you accessing `openfaas.demo`?

What machine is running `hey`?

**Comment by lreimer** [comment]
The `hey` command is running on my local machine.
The `openfaas.demo` URL points to a Traefik Ingress LoadBalancer IP. This simply is an entry in the `/etc/hosts` file.

**Comment by lreimer** [comment]
I spun up a fresh cluster. Only running OpenFaaS.
After I scaled the gateway deployment to 3 replicas, I now get these figures:
```
wrk -c 50 -t 4 -d 1m http://openfaas.demo/function/hello-openfaas

Running 1m test @ http://openfaas.demo/function/hello-openfaas
  4 threads and 50 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency   110.27ms  150.90ms   1.98s    90.07%
    Req/Sec   175.21     86.68   340.00     61.27%
  38868 requests in 1.00m, 9.27MB read
  Socket errors: connect 0, read 0, write 0, timeout 22
Requests/sec:    646.72
Transfer/sec:    157.89KB
```

**Comment by lreimer** [comment]
And here are the stats when calling the external-gateway directly:
```
wrk -c 50 -t 4 -d 1m http://35.189.......:8080/function/hello-openfaas
Running 1m test @ http://35.189........:8080/function/hello-openfaas
  4 threads and 50 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency    96.89ms  143.80ms   1.87s    92.36%
    Req/Sec   184.18     61.31   330.00     63.41%
  43988 requests in 1.00m, 10.49MB read
  Socket errors: connect 0, read 0, write 0, timeout 8
  Non-2xx or 3xx responses: 5
Requests/sec:    731.96
Transfer/sec:    178.70KB
```

**Comment by alexellis** [comment]
Please can you give me the numbers with `hey`?

**Comment by alexellis** [comment]
That looks better. I'm in the London area and I got this with `hey` which looks similar to your benchmark.

```
hey -c 50 -n 1000 http://35.:8080/function/hello-openfaas

Summary:
  Total:	1.2958 secs
  Slowest:	0.4419 secs
  Fastest:	0.0133 secs
  Average:	0.0445 secs
  Requests/sec:	771.7291
  
  Total data:	19000 bytes
  Size/request:	19 bytes

Response time histogram:
  0.013 [1]	|
  0.056 [884]	|■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■
  0.099 [57]	|■■■
  0.142 [2]	|
  0.185 [14]	|■
  0.228 [9]	|
  0.270 [1]	|
  0.313 [4]	|
  0.356 [1]	|
  0.399 [0]	|
  0.442 [27]	|■


Latency distribution:
  10% in 0.0194 secs
  25% in 0.0216 secs
  50% in 0.0250 secs
  75% in 0.0308 secs
  90% in 0.0722 secs
  95% in 0.1661 secs
  99% in 0.4262 secs

Details (average, fastest, slowest):
  DNS+dialup:	0.0030 secs, 0.0133 secs, 0.4419 secs
  DNS-lookup:	0.0000 secs, 0.0000 secs, 0.0000 secs
  req write:	0.0000 secs, 0.0000 secs, 0.0011 secs
  resp wait:	0.0414 secs, 0.0133 secs, 0.3923 secs
  resp read:	0.0000 secs, 0.0000 secs, 0.0018 secs

Status code distribution:
  [200]	1000 responses
```

Running for 1 minute

```
hey -c 50 -z 1m http://35.:8080/function/hello-openfaas

Summary:
  Total:	60.1399 secs
  Slowest:	2.4592 secs
  Fastest:	0.0127 secs
  Average:	0.0523 secs
  Requests/sec:	953.8596
  
  Total data:	1089935 bytes
  Size/request:	19 bytes

Response time histogram:
  0.013 [1]	|
  0.257 [56194]	|■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■
  0.502 [486]	|
  0.747 [355]	|
  0.991 [249]	|
  1.236 [50]	|
  1.481 [16]	|
  1.725 [9]	|
  1.970 [3]	|
  2.215 [0]	|
  2.459 [2]	|


Latency distribution:
  10% in 0.0213 secs
  25% in 0.0243 secs
  50% in 0.0301 secs
  75% in 0.0442 secs
  90% in 0.0688 secs
  95% in 0.1462 secs
  99% in 0.5855 secs

Details (average, fastest, slowest):
  DNS+dialup:	0.0000 secs, 0.0127 secs, 2.4592 secs
  DNS-lookup:	0.0000 secs, 0.0000 secs, 0.0000 secs
  req write:	0.0000 secs, 0.0000 secs, 0.0004 secs
  resp wait:	0.0522 secs, 0.0126 secs, 2.4591 secs
  resp read:	0.0000 secs, 0.0000 secs, 0.0004 secs

Status code distribution:
  [200]	57365 responses
```

**Comment by alexellis** [comment]
Hitting: `  Requests/sec:	953.8596`

**Comment by lreimer** [comment]
Same here. Berlin Airport seems to have a good connection. Here is what it will do:
1) extend the README, reference the performance section in the docs.
2) make the tunings transparent (labels on the function, scaled the gateway deployment)
3) Update the stats for OpenFaaS to 953 Requests/sec
4) Measure and update the performance stats for the other frameworks as well.

**Comment by lreimer** [comment]
Latest test results: 1041 Req/sec
I scaled the gateway to 5 replicas now. The Traefik gateway used by the other demos and frameworks is running as a daemon set on a 5 node cluster, so also 5 replicas here.

**Pull request merged**
